export const GET_TRAININGS = "GET_TRAININGS";
export const ADD_TRAINING = "ADD_TRAINING";
export const DELETE_TRAINING = "DELETE_TRAINING";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_TRAINING = "UPDATE_TRAINING";
export const FILTER_TRAINING = "FILTER_TRAINING";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const TRAINING_ERROR = "TRAINING_ERROR";
//auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
//bookings
export const GET_BOOKINGS_FOR_TRAINING = "GET_BOOKINGS_FOR_TRAINING";
export const ADD_BOOKING = "ADD_BOOKING";
export const REMOVE_BOOKING = "REMOVE_BOOKING";
export const BOOKING_ERROR = "BOOKING_ERROR";
export const CLEAR_BOOKING_ERRORS = "CLEAR_BOOKING_ERRORS";
export const ADD_BOOKING_MANUALLY = "ADD_BOOKING_MANUALLY";
